services:
  - type: web
    name: ionic-backend
    env: node
    buildCommand: npm install && npx prisma generate && npx @nestjs/cli build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false 